# # Site settings
# title: Anamaria Elek
email: anamariaelek@gmail.com
description: "© 2025 Anamaria Elek" 
# baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://anamaria.elek.hr" # the base hostname & protocol for your site
# twitter_username: anamariaelek
# github_username: anamariaelek
# linkedin_username: anamaria-elek
# cdn_url: #the url of the bucket or cdn which holds your photos
# # Build settings
# markdown: kramdown
permalink: pretty
main_img_url: https://anamaria-elek-hr.s3.eu-central-1.amazonaws.com/CRG_SYMPOSIUM2023_1083-EDIT.jpg
cdn_url: https://dmw492fxu64ad.cloudfront.net
