# # Site settings
title: My blog 
# email: #add email
# description: > # this means to ignore newlines until "baseurl:"
# baseurl: "" # the subpath of your site, e.g. /blog/
# # url: "http://andrew-max.com" # the base hostname & protocol for your site
# github_username: #git hub user name
# cdn_url: #the url of the bucket or cdn which holds your photos
# # Build settings
# markdown: kramdown
# permalink: pretty
main_img_url: https://pbs.twimg.com/profile_images/1296198361792552962/esjVB-hq_400x400.jpg
# Site settings

cdn_url: https://dmw492fxu64ad.cloudfront.net
