# # Site settings
title: Anamaria Elek
email: anamariaelek@gmail.com
description: "You're on Earth. There's no cure for that." 
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://anamaria.elek.hr" # the base hostname & protocol for your site
github_username: anamariaelek
# cdn_url: #the url of the bucket or cdn which holds your photos
# # Build settings
# markdown: kramdown
permalink: pretty
main_img_url: https://pbs.twimg.com/profile_images/1296198361792552962/esjVB-hq_400x400.jpg
cdn_url: https://dmw492fxu64ad.cloudfront.net
